import { getDb } from "../api/queries/connection";
import { papers } from "./schema";

const paperData = [
  { title: "A survey on vision transformer", authors: "K Han, Y Wang, H Chen, X Chen, J Guo, et al.", year: "2022", abstract: "Comprehensive survey of vision transformer architectures, applications, and variants.", url: "https://ieeexplore.ieee.org/abstract/document/9716741", citationCount: "5576", source: "Google Scholar", venue: "IEEE T-PAMI", topic: "Vision Transformer" },
  { title: "A review on the attention mechanism of deep learning", authors: "Z Niu, G Zhong, H Yu", year: "2021", abstract: "Review of attention mechanisms in deep learning with unified model definition.", url: "https://www.sciencedirect.com/science/article/pii/S092523122100477X", citationCount: "4097", source: "Google Scholar", venue: "Neurocomputing", topic: "Self-Attention" },
  { title: "Vision transformer with deformable attention", authors: "Z Xia, X Pan, S Song, LE Li, et al.", year: "2022", abstract: "Novel deformable self-attention for vision transformers with data-dependent key/value selection.", url: "https://openaccess.thecvf.com/content/CVPR2022/html/Xia_Vision_Transformer_With_Deformable_Attention_CVPR_2022_paper.html", citationCount: "1381", source: "Google Scholar", venue: "CVPR", topic: "Vision Transformer" },
  { title: "DeepViT: Towards deeper vision transformer", authors: "D Zhou, B Kang, X Jin, L Yang, X Lian, Z Jiang, et al.", year: "2021", abstract: "Techniques for training deeper vision transformers without attention collapse.", url: "https://arxiv.org/abs/2103.11886", citationCount: "932", source: "arXiv", venue: "arXiv", topic: "Vision Transformer" },
  { title: "A general survey on attention mechanisms in deep learning", authors: "G Brauwers, F Frasincar", year: "2021", abstract: "Comprehensive survey categorizing attention mechanisms with taxonomy and performance analysis.", url: "https://ieeexplore.ieee.org/abstract/document/9609539", citationCount: "876", source: "Google Scholar", venue: "IEEE TKDE", topic: "Self-Attention" },
  { title: "On the integration of self-attention and convolution", authors: "X Pan, C Ge, R Lu, S Song, G Chen, et al.", year: "2022", abstract: "Unified view of self-attention and convolution, showing they are two instances of the same principled framework.", url: "https://openaccess.thecvf.com/content/CVPR2022/html/Pan_On_the_Integration_of_Self-Attention_and_Convolution_CVPR_2022_paper.html", citationCount: "787", source: "Google Scholar", venue: "CVPR", topic: "Self-Attention" },
  { title: "Brain tumor segmentation based on deep learning and attention mechanism", authors: "R Ranjbarzadeh, A Bagherian Kasgari, et al.", year: "2021", abstract: "Multi-route deep learning with attention mechanism for brain tumor segmentation using MRI.", url: "https://www.nature.com/articles/s41598-021-90428-8", citationCount: "770", source: "Google Scholar", venue: "Scientific Reports", topic: "Medical Imaging" },
  { title: "UniFormer: Unifying convolution and self-attention", authors: "K Li, Y Wang, J Zhang, P Gao, G Song, et al.", year: "2023", abstract: "Unified transformer that seamlessly integrates convolution and self-attention for visual recognition.", url: "https://ieeexplore.ieee.org/abstract/document/10143709", citationCount: "757", source: "Google Scholar", venue: "IEEE T-PAMI", topic: "Vision Transformer" },
  { title: "Focal self-attention for local-global interactions in vision transformers", authors: "J Yang, C Li, P Zhang, X Dai, B Xiao, L Yuan, et al.", year: "2021", abstract: "Focal self-attention mechanism for efficient local-global interactions in vision transformers.", url: "https://arxiv.org/abs/2107.00641", citationCount: "702", source: "arXiv", venue: "arXiv", topic: "Vision Transformer" },
  { title: "Separable self-attention for mobile vision transformers", authors: "S Mehta, M Rastegari", year: "2022", abstract: "Optimizing self-attention in transformers for efficient mobile deployment.", url: "https://arxiv.org/abs/2206.02680", citationCount: "682", source: "arXiv", venue: "arXiv", topic: "Vision Transformer" },
  { title: "DaViT: Dual attention vision transformers", authors: "M Ding, B Xiao, N Codella, P Luo, J Wang, et al.", year: "2022", abstract: "Dual attention mechanism capturing spatial and channel contexts efficiently.", url: "https://openaccess.thecvf.com/content/ECCV2022/html/Ding_Davit_Dual_Attention_Vision_Transformers_ECCV_2022_paper.html", citationCount: "666", source: "Google Scholar", venue: "ECCV", topic: "Vision Transformer" },
  { title: "FLatten Transformer: Vision transformer using focused linear attention", authors: "D Han, X Pan, Y Han, S Song, et al.", year: "2023", abstract: "Linear attention with focus mechanism for efficient vision transformers.", url: "https://openaccess.thecvf.com/content/ICCV2023/html/Han_FLatten_Transformer_Vision_Transformer_using_Focused_Linear_Attention_ICCV_2023_paper.html", citationCount: "555", source: "Google Scholar", venue: "ICCV", topic: "Vision Transformer" },
  { title: "Synthesizer: Rethinking self-attention for transformer models", authors: "Y Tay, D Bahri, D Metzler, DC Juan, et al.", year: "2021", abstract: "Alternative to dot-product self-attention using learnable synthesizer mechanisms.", url: "https://proceedings.mlr.press/v139/tay21a.html", citationCount: "531", source: "Google Scholar", venue: "ICML", topic: "Self-Attention" },
  { title: "Shunted self-attention via multi-scale token aggregation", authors: "S Ren, D Zhou, S He, J Feng, et al.", year: "2022", abstract: "Multi-scale token aggregation for efficient self-attention in vision transformers.", url: "https://openaccess.thecvf.com/content/CVPR2022/html/Ren_Shunted_Self-Attention_via_Multi-Scale_Token_Aggregation_CVPR_2022_paper.html", citationCount: "481", source: "Google Scholar", venue: "CVPR", topic: "Vision Transformer" },
  { title: "A novel deep learning method based on attention mechanism for bearing remaining useful life prediction", authors: "Y Chen, G Peng, Z Zhu, S Li", year: "2020", abstract: "Attention-based deep learning for predicting remaining useful life of rolling bearings.", url: "https://www.sciencedirect.com/science/article/pii/S1568494619307008", citationCount: "460", source: "Google Scholar", venue: "Applied Soft Computing", topic: "Time Series" },
  { title: "Attention is All You Need", authors: "A Vaswani, N Shazeer, N Parmar, J Uszkoreit, L Jones, et al.", year: "2017", abstract: "The foundational transformer paper introducing self-attention mechanism.", url: "https://arxiv.org/abs/1706.03762", citationCount: "126000", source: "arXiv", venue: "NeurIPS", topic: "Self-Attention" },
  { title: "BERT: Pre-training of Deep Bidirectional Transformers", authors: "J Devlin, MW Chang, K Lee, K Toutanova", year: "2019", abstract: "Bidirectional encoder representations from transformers for language understanding.", url: "https://aclanthology.org/N19-1423/", citationCount: "149000", source: "Google Scholar", venue: "NAACL", topic: "NLP" },
  { title: "An Image is Worth 16x16 Words", authors: "A Dosovitskiy, L Beyer, A Kolesnikov, D Weissenborn, et al.", year: "2021", abstract: "Vision Transformer (ViT) applying transformers directly to image patches.", url: "https://openaccess.thecvf.com/content/ICCV2021/html/Dosovitskiy_An_Image_Is_Worth_16x16_Words_Transformers_for_Image_Recognition_ICCV_2021_paper.html", citationCount: "42000", source: "Google Scholar", venue: "ICCV", topic: "Vision Transformer" },
  { title: "Swin Transformer: Hierarchical Vision Transformer", authors: "Z Liu, Y Lin, Y Cao, H Hu, Y Wei, et al.", year: "2021", abstract: "Hierarchical transformer with shifted windows for efficient visual recognition.", url: "https://openaccess.thecvf.com/content/ICCV2021/html/Liu_Swin_Transformer_Hierarchical_Vision_Transformer_Using_Shifted_Windows_ICCV_2021_paper.html", citationCount: "24000", source: "Google Scholar", venue: "ICCV", topic: "Vision Transformer" },
  { title: "Multi-Head Attention with Diversity", authors: "X Li, S Zheng, C Yang, et al.", year: "2020", abstract: "Improving multi-head attention through diversity-promoting regularization.", url: "https://proceedings.neurips.cc/paper/2020", citationCount: "320", source: "Google Scholar", venue: "NeurIPS", topic: "Self-Attention" },
  { title: "Attention U-Net: Learning Where to Look for the Pancreas", authors: "O Oktay, J Schlemper, LL Folgoc, M Lee, et al.", year: "2018", abstract: "Attention gates for medical image segmentation focusing on target regions.", url: "https://arxiv.org/abs/1804.03999", citationCount: "8900", source: "arXiv", venue: "MICCAI", topic: "Medical Imaging" },
  { title: "CBAM: Convolutional Block Attention Module", authors: "S Woo, J Park, JY Lee, IS Kweon", year: "2018", abstract: "Channel and spatial attention module for convolutional neural networks.", url: "https://openaccess.thecvf.com/content_ECCV_2018/html/Sanghyun_Woo_Convolutional_Block_Attention_ECCV_2018_paper.html", citationCount: "18500", source: "Google Scholar", venue: "ECCV", topic: "Self-Attention" },
  { title: "Non-local Neural Networks", authors: "X Wang, R Girshick, A Gupta, K He", year: "2018", abstract: "Capturing long-range dependencies with non-local operations inspired by self-attention.", url: "https://openaccess.thecvf.com/content_cvpr_2018/html/Wang_Non-Local_Neural_Networks_CVPR_2018_paper.html", citationCount: "11800", source: "Google Scholar", venue: "CVPR", topic: "Self-Attention" },
  { title: "Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context", authors: "Z Dai, Z Yang, Y Yang, J Carbonell, Q Le, R Salakhutdinov", year: "2019", abstract: "Segment-level recurrence and relative positioning for longer context in transformers.", url: "https://arxiv.org/abs/1901.02860", citationCount: "7200", source: "arXiv", venue: "ACL", topic: "NLP" },
  { title: "Informer: Beyond Efficient Transformer for Long Sequence Time-Series Forecasting", authors: "H Zhou, S Zhang, J Peng, S Zhang, J Li, H Xiong, W Zhang", year: "2021", abstract: "Efficient transformer for long sequence time-series forecasting with ProbSparse attention.", url: "https://ojs.aaai.org/index.php/AAAI/article/view/17325", citationCount: "4800", source: "Google Scholar", venue: "AAAI", topic: "Time Series" },
  { title: "Graph Attention Networks", authors: "P Velickovic, G Cucurull, A Casanova, A Romero, P Lio, Y Bengio", year: "2018", abstract: "Attention mechanisms for graph-structured data using masked self-attentional layers.", url: "https://openaccess.thecvf.com/content_ICLR_2018/papers/Velickovic_Graph_Attention_Networks_ICLR_2018_paper.pdf", citationCount: "21400", source: "Google Scholar", venue: "ICLR", topic: "Self-Attention" },
  { title: "RoFormer: Enhanced Transformer with Rotary Position Embedding", authors: "J Su, Y Lu, S Pan, A Murtadha, B Wen, Y Liu", year: "2021", abstract: "Rotary position embedding for enhanced transformer architecture.", url: "https://arxiv.org/abs/2104.09864", citationCount: "1200", source: "arXiv", venue: "NeurIPS", topic: "NLP" },
  { title: "Scaling Vision Transformers", authors: "X Zhai, A Kolesnikov, N Houlsby, L Beyer", year: "2022", abstract: "Techniques for scaling vision transformers to achieve improved performance.", url: "https://openaccess.thecvf.com/content/CVPR2022/html/Zhai_Scaling_Vision_Transformers_CVPR_2022_paper.html", citationCount: "2100", source: "Google Scholar", venue: "CVPR", topic: "Vision Transformer" },
  { title: "MobileViT: Light-weight, General-purpose, and Mobile-friendly Vision Transformer", authors: "S Mehta, M Rastegari", year: "2022", abstract: "Light-weight vision transformer combining CNNs and transformers for mobile devices.", url: "https://openaccess.thecvf.com/content/CVPR2022/html/Mehta_MobileViT_Light-Weight_and_General-Purpose_Vision_Transformer_CVPR_2022_paper.html", citationCount: "2800", source: "Google Scholar", venue: "CVPR", topic: "Vision Transformer" },
  { title: "MaxViT: Multi-Axis Vision Transformer", authors: "Z Tu, H Talebi, H Zhang, F Yang, P Milanfar, A Bovik, Y Li", year: "2022", abstract: "Multi-axis attention combining blocked local and dilated global attention.", url: "https://openaccess.thecvf.com/content/ECCV2022/html/Tu_MaxViT_Multi-Axis_Vision_Transformer_ECCV_2022_paper.html", citationCount: "1100", source: "Google Scholar", venue: "ECCV", topic: "Vision Transformer" },
];

async function seed() {
  const db = getDb();
  console.log(`Seeding ${paperData.length} papers...`);

  // Clear existing
  await db.delete(papers);

  // Insert all
  for (const paper of paperData) {
    await db.insert(papers).values(paper);
  }

  console.log("Done! Papers seeded.");
}

seed().catch(console.error);
