// Legacy Node/MySQL seed entry point. Production (Cloudflare D1) seeding uses
// db/seed.sql, regenerated by scripts/generate-seed-papers.mjs.

async function seed() {
  console.log("Seeding database...");

  // TODO: insert seed data via getDb() from "../api/queries/connection", e.g.
  // await db.insert(schema.papers).values([...]);

  console.log("Done.");
  process.exit(0); // close MySQL connection pool
}

seed();
